### ISSUE TITLE
ERROR in ./client/index.tsx

### ISSUE THREAD

**Issue by MuhAssar** [phuoc-ng/csslayout#143]
I just cloned the repo and did **npm i** then **npm run dev-server**
windows 10 2004 x64

```
ERROR in ./client/index.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in D:\Temp\csslayout\node_modules\@babel\helper-compil
ation-targets\package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Temp\csslayout\node_modules\@babel\preset-env\lib\debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [LvDl] ./node_modules/lodash/lodash.js 530 KiB {0} [built]
    [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
    [yLpj] (webpack)/buildin/global.js 472 bytes {0} [built]
    [z0BS] ./node_modules/html-webpack-plugin/lib/loader.js!./client/index.html 910 bytes {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/postcss-loader/src/index.js??postcss!vend
ors/highlight.js@9.12.0/theme.min.css:
    Entrypoint mini-css-extract-plugin = *
    [JPst] ./node_modules/css-loader/dist/runtime/api.js 2.46 KiB {mini-css-extract-plugin} [built]
    [wP9d] ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??postcss!./vendors/highlight.js@9.12.
0/theme.min.css 1.33 KiB {mini-css-extract-plugin} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/postcss-loader/src/index.js??postcss!vend
ors/tailwind@1.1.4/tailwind.css:
    Entrypoint mini-css-extract-plugin = *
    [JPst] ./node_modules/css-loader/dist/runtime/api.js 2.46 KiB {mini-css-extract-plugin} [built]
    [P+/v] ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??postcss!./vendors/tailwind@1.1.4/tai
lwind.css 598 KiB {mini-css-extract-plugin} [built]
i ｢wdm｣: Failed to compile.
```

**Comment by designow** [comment]
I have similar problems

`ERROR in ./client/index.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in D:\Best_practice\csslayout\node_modules\@babel\helper-compilation-targets\package.json
    at applyExports (internal/modules/cjs/loader.js:498:9)
    at resolveExports (internal/modules/cjs/loader.js:514:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:642:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1017:27)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (D:\Best_practice\csslayout\node_modules\@babel\preset-env\lib\debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [LvDl] ./node_modules/lodash/lodash.js 530 KiB {0} [built]
    [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
    [yLpj] (webpack)/buildin/global.js 472 bytes {0} [built]
    [z0BS] ./node_modules/html-webpack-plugin/lib/loader.js!./client/index.html 910 bytes {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/postcss-loader/src/index.js??postcss!vendors/highlight.js@9.12.0/theme.min.css:
    Entrypoint mini-css-extract-plugin = *
    [JPst] ./node_modules/css-loader/dist/runtime/api.js 2.46 KiB {mini-css-extract-plugin} [built]
    [wP9d] ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??postcss!./vendors/highlight.js@9.12.0/theme.min.css 1.33 KiB {mini-css-extract-plugin} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/postcss-loader/src/index.js??postcss!vendors/tailwind@1.1.4/tailwind.css:
    Entrypoint mini-css-extract-plugin = *
    [JPst] ./node_modules/css-loader/dist/runtime/api.js 2.46 KiB {mini-css-extract-plugin} [built]
    [P+/v] ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??postcss!./vendors/tailwind@1.1.4/tailwind.css 598 KiB {mini-css-extract-plugin} [built]
i ｢wdm｣: Failed to compile.
`

**Comment by designow** [comment]
i solved the problem with: 
npm install @babel/helper-compilation-targets --save-dev

**Comment by EasonPai** [comment]
No luck for me...

**Comment by phuoc-ng** [comment]
Please try again! The repos just gets a big updates and everything should works
