### ISSUE TITLE
项目依赖安装报错

### ISSUE THREAD

**Issue by CodeDreamfy** [phuoc-ng/csslayout#159]
无论是使用`npm i`还是`yarn install`,即使使用了`nrm ls`进行更换源，进行依赖安装仍然报错，依赖装不上。

`npm`版本：6.7.0
`yarn`版本：1.22.5
`node`版本：11.14.0
`系统环境`：macOS Catalina 10.15.7

错误提示：
```bash
> puppeteer@1.20.0 install /Users/CodeDream/github/css/csslayout-master/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: connect ETIMEDOUT 172.217.161.176:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/Users/CodeDream/github/css/csslayout-master/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/Users/CodeDream/github/css/csslayout-master/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
  errno: 'ETIMEDOUT',
```

**Comment by phuoc-ng** [comment]
Please try again! I just updated the repos, and now everything should work on macOS.
